# 修复 opkg 软件源 404 问题
# hanwckf/immortalwrt-mt798x 是定制 fork，公网没有对应软件包
# 注释掉所有无效远端源，避免 opkg update 报错
# 2026-05-31

# src/gz openwrt_packages https://mirrors.ustc.edu.cn/immortalwrt/releases/24.10-SNAPSHOT/packages/aarch64_cortex-a53/base
# src/gz openwrt_luci https://mirrors.ustc.edu.cn/immortalwrt/releases/24.10-SNAPSHOT/packages/aarch64_cortex-a53/luci
# src/gz openwrt_routing https://mirrors.ustc.edu.cn/immortalwrt/releases/24.10-SNAPSHOT/packages/aarch64_cortex-a53/routing
# src/gz openwrt_telephony https://mirrors.ustc.edu.cn/immortalwrt/releases/24.10-SNAPSHOT/packages/aarch64_cortex-a53/telephony
